package:
  name: zipline
  version: 0.8.3

source:
  fn: zipline-0.8.3.tar.gz
  url: https://pypi.python.org/packages/source/z/zipline/zipline-0.8.3.tar.gz
  md5: 042ffcee614d2279add9a1bfd27a33cf

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
    - pytz
    - requests
    - numpy
    - pandas
    - scipy
    - matplotlib
    - logbook

test:
  # Python imports
  imports:
    - zipline

about:
  home: https://zipline.io
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
